# Accessible by: eventstore-svc.eventstore.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: eventstore-svc
  namespace: eventstore
  labels:
    name: eventstore
spec:
  ports:
  - port: 2113
    targetPort: 2113
    protocol: TCP
  selector:
    role: eventstore-server
